//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EscolaDeFormacaoPUC.Persistencia
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aluno
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Aluno()
        {
            this.AlunoCurso = new HashSet<AlunoCurso>();
        }
    
        public int IDAluno { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public System.DateTime DataNascimento { get; set; }
        public string Escolaridade { get; set; }
        public string Endereco { get; set; }
        public Nullable<int> IDResponsavel { get; set; }
        public string FoneFixo { get; set; }
        public string FoneCelular { get; set; }
    
        public virtual Responsavel Responsavel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AlunoCurso> AlunoCurso { get; set; }
    }
}
